"""Add category_ids to products

Revision ID: 0185bdd95aaa
Revises: c1d2e3f4g5h6
Create Date: 2026-05-27 15:51:36.326840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0185bdd95aaa'
down_revision: Union[str, None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('idx_cart_items_user_id'), table_name='cart_items')
    op.drop_index(op.f('idx_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('idx_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('idx_orders_created_at'), table_name='orders')
    op.drop_index(op.f('idx_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.drop_index(op.f('idx_orders_user_id'), table_name='orders')
    op.add_column('products', sa.Column('category_ids', sa.JSON(), nullable=True))
    op.alter_column('products', 'gst_percentage',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('18'))
    op.drop_index(op.f('idx_products_active_featured'), table_name='products')
    op.drop_index(op.f('idx_products_category_id'), table_name='products')
    op.drop_index(op.f('idx_products_is_active'), table_name='products')
    op.drop_index(op.f('idx_products_is_featured'), table_name='products', postgresql_where='(is_featured = true)')
    op.drop_index(op.f('idx_products_seller_id'), table_name='products')
    op.drop_constraint(op.f('fk_products_seller_id_users'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'])
    op.drop_constraint(op.f('promo_codes_code_key'), 'promo_codes', type_='unique')
    op.drop_index(op.f('idx_wishlist_items_user_id'), table_name='wishlist_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_wishlist_items_user_id'), 'wishlist_items', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('promo_codes_code_key'), 'promo_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_products_seller_id_users'), 'products', 'users', ['seller_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.create_index(op.f('idx_products_is_featured'), 'products', ['is_featured'], unique=False, postgresql_where='(is_featured = true)')
    op.create_index(op.f('idx_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('idx_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('idx_products_active_featured'), 'products', ['is_active', 'is_featured'], unique=False)
    op.alter_column('products', 'gst_percentage',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('18'))
    op.drop_column('products', 'category_ids')
    op.create_index(op.f('idx_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('idx_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('idx_orders_created_at'), 'orders', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('idx_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('idx_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.create_index(op.f('idx_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    # ### end Alembic commands ###
